#!/bin/bash

BIN_DIR="$(dirname $BASH_SOURCE[0])"
RUN_DIR="$(dirname $BIN_DIR)"

cd "$RUN_DIR"

# If no -l or -v option is specified for sel_ldr, silence the log by default.
SILENCE_LOG="-l /dev/null"

# Scan options recognized by sel_ldr (we only need to list those that take an
# argument).
while getopts ":h:r:w:i:f:l:m:E:v" opt; do
  case "$opt" in
    l|v) SILENCE_LOG="";;
  esac
done

LAST_SL_ARG=$((OPTIND-1))
if [[ "${!LAST_SL_ARG}" == "--" ]]; then
  LAST_SL_ARG=$((LAST_SL_ARG-1))
fi

SEL_LDR_FLAGS=${@:1:$LAST_SL_ARG}
ARGS=("${@:$OPTIND}")

if [[ ${#ARGS[@]} -eq 0 ]]; then
  echo "Usage: $0 [options] program args..."
  echo "  Program must be within the sandbox root of $RUN_DIR/root."
  echo
  exec bin/sel_ldr -?
fi


# Change to the directory of the script, which should be the build directory.
echo bin/sel_ldr -m root -B lib/irt_core.nexe $SEL_LDR_FLAGS $SILENCE_LOG lib/runnable-ld.so --library-path /slib "${ARGS[@]}"
exec bin/sel_ldr -m root -B lib/irt_core.nexe $SEL_LDR_FLAGS $SILENCE_LOG lib/runnable-ld.so --library-path /slib "${ARGS[@]}"
